{
  "hash": "a2fc77062e4706b53b0ace432d76ed47",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploratory Data Analysis I\"\nsubtitle: \"Lecture 4\"\ndate: \"2026-07-06\"\nformat: \n  revealjs:\n    output-file: 04-exploratory-data-analysis-I-slides.html\n  html:\n    output-file: 04-exploratory-data-analysis-I.html\nauto-stretch: false\n---\n\n\n<!-- begin: ae definition -->\n\n\n\n\n\n<!-- end: ae definition -->\n\n## Announcements\n\n- Lab 1 due Wednesday 11:59 pm\n- Office hours start this week!\n- No lab today (Lab 2 on Thursday)\n- AE attendance starts today (make sure you come to class and commit push before 10:45am)\n\n## What is Exploratory Data Analysis? {.smaller}\n\n- EDA is like a playground\n- I call it a free for all where you are playing around with the data\n- Goal isn't to draw conclusions, but rather get a sense of your data and what questions it may be able to answer.\n- Iterate between generating questions about your data, searching for answers via visualizing, transforming, and modeling, and refining/updating original questions\n- More https://r4ds.hadley.nz/EDA.html\n\n## Packages {.smaller}\n\n-   For the data: [**usdata**](https://openintrostat.github.io/usdata/)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(usdata)\n```\n:::\n\n\n-   For the exploratory data analysis (EDA): [**tidyverse**](https://www.tidyverse.org/packages/) and [**ggthemes**](https://jrnold.github.io/ggthemes/)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ──────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggthemes)\n```\n:::\n\n\n## Data: `gerrymander` {.small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 12\n   district last_name first_name party16 clinton16 trump16 dem16 state\n   <chr>    <chr>     <chr>      <chr>       <dbl>   <dbl> <dbl> <chr>\n 1 AK-AL    Young     Don        R            37.6    52.8     0 AK   \n 2 AL-01    Byrne     Bradley    R            34.1    63.5     0 AL   \n 3 AL-02    Roby      Martha     R            33      64.9     0 AL   \n 4 AL-03    Rogers    Mike D.    R            32.3    65.3     0 AL   \n 5 AL-04    Aderholt  Rob        R            17.4    80.4     0 AL   \n 6 AL-05    Brooks    Mo         R            31.3    64.7     0 AL   \n 7 AL-06    Palmer    Gary       R            26.1    70.8     0 AL   \n 8 AL-07    Sewell    Terri      D            69.8    28.6     1 AL   \n 9 AR-01    Crawford  Rick       R            30.2    65       0 AR   \n10 AR-02    Hill      French     R            41.7    52.4     0 AR   \n# ℹ 425 more rows\n# ℹ 4 more variables: party18 <chr>, dem18 <dbl>, flip18 <dbl>,\n#   gerry <fct>\n```\n\n\n:::\n:::\n\n\n## What is gerrymandering?\n\n::: {style=\"display: flex; justify-content: center;\"}\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/bGLRJ12uqmk?si=DAoLH-0Cwd2yg1LL\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen>\n\n</iframe>\n:::\n\n## (Latest) Gerrymandering in NC\n\n![](img/04/gerry_NC_2.jpeg){fig-align=\"center\" width=\"50%\"}\n\n## Data: `gerrymander` {.scrollable .smaller .incremental}\n\n::: question\nWhat is a good first function to use to get to know a dataset?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(gerrymander)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 435\nColumns: 12\n$ district   <chr> \"AK-AL\", \"AL-01\", \"AL-02\", \"AL-03\", \"AL-04\", \"AL-…\n$ last_name  <chr> \"Young\", \"Byrne\", \"Roby\", \"Rogers\", \"Aderholt\", \"…\n$ first_name <chr> \"Don\", \"Bradley\", \"Martha\", \"Mike D.\", \"Rob\", \"Mo…\n$ party16    <chr> \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"D\", \"R\", \"R\",…\n$ clinton16  <dbl> 37.6, 34.1, 33.0, 32.3, 17.4, 31.3, 26.1, 69.8, 3…\n$ trump16    <dbl> 52.8, 63.5, 64.9, 65.3, 80.4, 64.7, 70.8, 28.6, 6…\n$ dem16      <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0…\n$ state      <chr> \"AK\", \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"…\n$ party18    <chr> \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"D\", \"R\", \"R\",…\n$ dem18      <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0…\n$ flip18     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0…\n$ gerry      <fct> mid, high, high, high, high, high, high, high, mi…\n```\n\n\n:::\n:::\n\n\n## Data: `gerrymander` {.scrollable .medium}\n\n-   Rows: Congressional districts\n\n-   Columns:\n\n    -   Congressional district and state\n\n    -   2016 election: winning party, % for Clinton, % for Trump, whether a Democrat won the House election, name of election winner\n\n    -   2018 election: winning party, whether a Democrat won the 2018 House election\n\n    -   Whether a Democrat flipped the seat in the 2018 election\n\n    -   Prevalence of gerrymandering: low, mid, and high\n\n## Overview of Data Types {.scrollable .medium}\n\n-   ***Numerical Data:***\n\n    -   Takes a wide range of numerical values\n\n    -   Makes sense to add, subtract, etc.\n\n    -   Can be either discrete (e.g., integers) or continuous\n\n-   ***Categorical Data:***\n\n    -   Values can be thought of as distinct categories\n\n    -   The possible values are called ***levels***\n\n    -   Binary data is a subset of categorical data with 2 levels (e.g., 0/1, T/F, yes/no)\n\n    -   Ordinal data is a subset of categorical data in which there is some inherent \"ordering\" to the levels (e.g., pain, where pain can be \"low\", \"medium\", or \"high\"; letter grades, where A \\> B \\> C \\> ... \\> F)\n\n## Variable types: `district`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                         |\n|--------------|------------------------------|\n| `district`   | [categorical, ID]{.fragment} |\n| `last_name`  |                              |\n| `first_name` |                              |\n| `party16`    |                              |\n| `clinton16`  |                              |\n| `trump16`    |                              |\n| `dem16`      |                              |\n| `state`      |                              |\n| `party18`    |                              |\n| `dem18`      |                              |\n| `flip18`     |                              |\n| `gerry`      |                              |\n:::\n\n::: {.column .small}\nCongressional district:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   district\n   <chr>   \n 1 AK-AL   \n 2 AL-01   \n 3 AL-02   \n 4 AL-03   \n 5 AL-04   \n 6 AL-05   \n 7 AL-06   \n 8 AL-07   \n 9 AR-01   \n10 AR-02   \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `last_name`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                         |\n|--------------|------------------------------|\n| `district`   | categorical, ID              |\n| `last_name`  | [categorical, ID]{.fragment} |\n| `first_name` |                              |\n| `party16`    |                              |\n| `clinton16`  |                              |\n| `trump16`    |                              |\n| `dem16`      |                              |\n| `state`      |                              |\n| `party18`    |                              |\n| `dem18`      |                              |\n| `flip18`     |                              |\n| `gerry`      |                              |\n:::\n\n::: {.column .small}\nLast name of 2016 election winner:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(last_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   last_name\n   <chr>    \n 1 Young    \n 2 Byrne    \n 3 Roby     \n 4 Rogers   \n 5 Aderholt \n 6 Brooks   \n 7 Palmer   \n 8 Sewell   \n 9 Crawford \n10 Hill     \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `first_name`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                         |\n|--------------|------------------------------|\n| `district`   | categorical, ID              |\n| `last_name`  | categorical, ID              |\n| `first_name` | [categorical, ID]{.fragment} |\n| `party16`    |                              |\n| `clinton16`  |                              |\n| `trump16`    |                              |\n| `dem16`      |                              |\n| `state`      |                              |\n| `party18`    |                              |\n| `dem18`      |                              |\n| `flip18`     |                              |\n| `gerry`      |                              |\n:::\n\n::: {.column .small}\nFirst name of 2016 election winner:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(first_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   first_name\n   <chr>     \n 1 Don       \n 2 Bradley   \n 3 Martha    \n 4 Mike D.   \n 5 Rob       \n 6 Mo        \n 7 Gary      \n 8 Terri     \n 9 Rick      \n10 French    \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `party16`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                     |\n|--------------|--------------------------|\n| `district`   | categorical, ID          |\n| `last_name`  | categorical, ID          |\n| `first_name` | categorical, ID          |\n| `party16`    | [categorical]{.fragment} |\n| `clinton16`  |                          |\n| `trump16`    |                          |\n| `dem16`      |                          |\n| `state`      |                          |\n| `party18`    |                          |\n| `dem18`      |                          |\n| `flip18`     |                          |\n| `gerry`      |                          |\n:::\n\n::: {.column .small}\nPolitical party of 2016 election winner:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(party16)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   party16\n   <chr>  \n 1 R      \n 2 R      \n 3 R      \n 4 R      \n 5 R      \n 6 R      \n 7 R      \n 8 D      \n 9 R      \n10 R      \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `clinton16`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                               |\n|--------------|------------------------------------|\n| `district`   | categorical, ID                    |\n| `last_name`  | categorical, ID                    |\n| `first_name` | categorical, ID                    |\n| `party16`    | categorical                        |\n| `clinton16`  | [numerical, continuous]{.fragment} |\n| `trump16`    |                                    |\n| `dem16`      |                                    |\n| `state`      |                                    |\n| `party18`    |                                    |\n| `dem18`      |                                    |\n| `flip18`     |                                    |\n| `gerry`      |                                    |\n:::\n\n::: {.column .small}\nPercent of vote received by Clinton in 2016 Presidential Election:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(clinton16)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   clinton16\n       <dbl>\n 1      37.6\n 2      34.1\n 3      33  \n 4      32.3\n 5      17.4\n 6      31.3\n 7      26.1\n 8      69.8\n 9      30.2\n10      41.7\n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `trump16`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                               |\n|--------------|------------------------------------|\n| `district`   | categorical, ID                    |\n| `last_name`  | categorical, ID                    |\n| `first_name` | categorical, ID                    |\n| `party16`    | categorical                        |\n| `clinton16`  | numerical, continuous              |\n| `trump16`    | [numerical, continuous]{.fragment} |\n| `dem16`      |                                    |\n| `state`      |                                    |\n| `party18`    |                                    |\n| `dem18`      |                                    |\n| `flip18`     |                                    |\n| `gerry`      |                                    |\n:::\n\n::: {.column .small}\nPercent of vote received by Trump in 2016 Presidential Election:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(trump16)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   trump16\n     <dbl>\n 1    52.8\n 2    63.5\n 3    64.9\n 4    65.3\n 5    80.4\n 6    64.7\n 7    70.8\n 8    28.6\n 9    65  \n10    52.4\n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `dem16`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                             |\n|--------------|----------------------------------|\n| `district`   | categorical, ID                  |\n| `last_name`  | categorical, ID                  |\n| `first_name` | categorical, ID                  |\n| `party16`    | categorical                      |\n| `clinton16`  | numerical, continuous            |\n| `trump16`    | numerical, continuous            |\n| `dem16`      | [categorical, binary]{.fragment} |\n| `state`      |                                  |\n| `party18`    |                                  |\n| `dem18`      |                                  |\n| `flip18`     |                                  |\n| `gerry`      |                                  |\n:::\n\n::: {.column .small}\nDid a Democrat win the 2016 House election.\nLevels of 1 (yes) and 0 (no):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(dem16)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   dem16\n   <dbl>\n 1     0\n 2     0\n 3     0\n 4     0\n 5     0\n 6     0\n 7     0\n 8     1\n 9     0\n10     0\n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `state`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                     |\n|--------------|--------------------------|\n| `district`   | categorical, ID          |\n| `last_name`  | categorical, ID          |\n| `first_name` | categorical, ID          |\n| `party16`    | categorical              |\n| `clinton16`  | numerical, continuous    |\n| `trump16`    | numerical, continuous    |\n| `dem16`      | categorical, binary      |\n| `state`      | [categorical]{.fragment} |\n| `party18`    |                          |\n| `dem18`      |                          |\n| `flip18`     |                          |\n| `gerry`      |                          |\n:::\n\n::: {.column .small}\nState the Representative is from:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(state)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   state\n   <chr>\n 1 AK   \n 2 AL   \n 3 AL   \n 4 AL   \n 5 AL   \n 6 AL   \n 7 AL   \n 8 AL   \n 9 AR   \n10 AR   \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `party18`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                             |\n|--------------|----------------------------------|\n| `district`   | categorical, ID                  |\n| `last_name`  | categorical, ID                  |\n| `first_name` | categorical, ID                  |\n| `party16`    | categorical                      |\n| `clinton16`  | numerical, continuous            |\n| `trump16`    | numerical, continuous            |\n| `dem16`      | categorical, binary              |\n| `state`      | categorical                      |\n| `party18`    | [categorical, binary]{.fragment} |\n| `dem18`      |                                  |\n| `flip18`     |                                  |\n| `gerry`      |                                  |\n:::\n\n::: {.column .small}\nPolitical Party of the 2018 election winner:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(party18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   party18\n   <chr>  \n 1 R      \n 2 R      \n 3 R      \n 4 R      \n 5 R      \n 6 R      \n 7 R      \n 8 D      \n 9 R      \n10 R      \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `dem18`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                             |\n|--------------|----------------------------------|\n| `district`   | categorical, ID                  |\n| `last_name`  | categorical, ID                  |\n| `first_name` | categorical, ID                  |\n| `party16`    | categorical                      |\n| `clinton16`  | numerical, continuous            |\n| `trump16`    | numerical, continuous            |\n| `dem16`      | categorical, binary              |\n| `state`      | categorical                      |\n| `party18`    | categorical, binary              |\n| `dem18`      | [categorical, binary]{.fragment} |\n| `flip18`     |                                  |\n| `gerry`      |                                  |\n:::\n\n::: {.column .small}\nDid a Democrat win the 2018 House election.\nLevels of 1 (yes) and 0 (no):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(dem18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   dem18\n   <dbl>\n 1     0\n 2     0\n 3     0\n 4     0\n 5     0\n 6     0\n 7     0\n 8     1\n 9     0\n10     0\n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `flip18`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                     |\n|--------------|--------------------------|\n| `district`   | categorical, ID          |\n| `last_name`  | categorical, ID          |\n| `first_name` | categorical, ID          |\n| `party16`    | categorical              |\n| `clinton16`  | numerical, continuous    |\n| `trump16`    | numerical, continuous    |\n| `dem16`      | categorical, binary      |\n| `state`      | categorical              |\n| `party18`    | categorical, binary      |\n| `dem18`      | categorical, binary      |\n| `flip18`     | [categorical]{.fragment} |\n| `gerry`      |                          |\n:::\n\n::: {.column .small}\nIn the 2018 election, did the seat flip from D to R (-1), from R to D (1), or not change (0)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(flip18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   flip18\n    <dbl>\n 1      0\n 2      0\n 3      0\n 4      0\n 5      0\n 6      0\n 7      0\n 8      0\n 9      0\n10      0\n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Variable types: `gerry`\n\n::: columns\n::: {.column .xsmall}\n| Variable     | Type                              |\n|--------------|-----------------------------------|\n| `district`   | categorical, ID                   |\n| `last_name`  | categorical, ID                   |\n| `first_name` | categorical, ID                   |\n| `party16`    | categorical                       |\n| `clinton16`  | numerical, continuous             |\n| `trump16`    | numerical, continuous             |\n| `dem16`      | categorical, binary               |\n| `state`      | categorical                       |\n| `party18`    | categorical, binary               |\n| `dem18`      | categorical, binary               |\n| `flip18`     | categorical                       |\n| `gerry`      | [categorical, ordinal]{.fragment} |\n:::\n\n::: {.column .small}\nCategorical variable for prevalence of gerrymandering with levels of low, mid and high:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(gerry)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 435 × 1\n   gerry\n   <fct>\n 1 mid  \n 2 high \n 3 high \n 4 high \n 5 high \n 6 high \n 7 high \n 8 high \n 9 mid  \n10 mid  \n# ℹ 425 more rows\n```\n\n\n:::\n:::\n\n:::\n:::\n\n# Univariate analysis\n\n## Univariate analysis\n\nAnalyzing a single variable:\n\n::: incremental\n-   Numerical: histogram, box plot, density plot, etc.\n\n-   Categorical: bar plot, pie chart, etc.\n:::\n\n## Histogram - Step 1 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 2 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16))\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 3 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 4 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram(binwidth = 1)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 4 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram(binwidth = 100)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 4 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram(binwidth = 3)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 4 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram(binwidth = 5)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n## Histogram - Step 5 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3-8\"}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram(binwidth = 5) +\n  labs(\n    title = \"Percent of vote received by Trump in 2016 Presidential Election\",\n    subtitle = \"From each Congressional District\",\n    x = \"Percent of vote\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-25-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 1 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-26-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 2 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16))\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-27-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 3 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n\n## Contrast that with the histogram {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_histogram(aes(y = after_stat(density))) + \n  geom_density(color = \"red\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n\nPrettier.\nSmooths out the lumps and bumps.\nThere are still defaults you could learn to override.\n\n## Density plot - Step 4 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"red\")\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-30-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 5 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\")\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-31-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 6 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\", alpha = 1)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-32-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 6 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\", alpha = 0)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-33-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 6 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\", alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-34-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 7 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\", alpha = 0.5, linewidth = 2)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-35-1.png){width=960}\n:::\n:::\n\n\n## Density plot - Step 8 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3-8\"}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\", alpha = 0.5, linewidth = 2) +\n  labs(\n    title = \"Percent of vote received by Trump in 2016 Presidential Election\",\n    subtitle = \"From each Congressional District\",\n    x = \"Percent of vote\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-36-1.png){width=960}\n:::\n:::\n\n\n## \"Describe a distribution\"\n\n![](img/04/name_a_woman.jpeg){fig-align=\"center\" width=\"50%\"}\n\n## \"Describe a distribution\"\n\n::: callout-tip\nWhen answering a question that prompts you to \"describe a distribution\", you should ensure that your narrative mentions each of the following:\n\n1)  Shape (this includes modality & skew)\n2)  Outliers\n3)  Center\n4)  Spread\n:::\n\nor \"remember your SOCS\"\n\n## Example: The Standard Normal Distribution {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-37-1.png){width=2400}\n:::\n:::\n\n\n## Example: The Standard Normal Distribution {.smaller}\n\n::: columns\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-38-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n::: incremental\n1.  Symmetric (about it's center); unimodal (one peak)\n2.  No apparent outliers\n3.  Centered at 0 (mean and median agree)\n4.  Values range between -3 and +3, roughly\n:::\n:::\n:::\n\n## Back to Gerry\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-39-1.png){width=960}\n:::\n:::\n\n\n## \"Skewed\" data\n\n::: columns\n::: {.column width=\"47.5%\"}\n![](img/04/left-skew.png){fig-align=\"center\" width=\"90%\"}\n:::\n\n::: {.column width=\"45%\"}\n![](img/04/right-skew.jpg){fig-align=\"center\" width=\"100%\"}\n:::\n:::\n\n## Box plot - Step 1 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-40-1.png){width=960}\n:::\n:::\n\n\n## Box plot - Step 2 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16))\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-41-1.png){width=960}\n:::\n:::\n\n\n## Box plot - Step 3 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-42-1.png){width=960}\n:::\n:::\n\n\n## Box plot - Alternative Step 2 + 3 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(y = trump16)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-43-1.png){width=960}\n:::\n:::\n\n\n## Box plot - Step 4 {.smaller .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3-8\"}\nggplot(gerrymander, aes(x = trump16)) +\n  geom_boxplot() +\n  labs(\n    title = \"Percent of vote received by Trump in 2016 Presidential Election\",\n    subtitle = \"From each Congressional District\",\n    x = \"Percent of vote\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-44-1.png){width=960}\n:::\n:::\n\n\n## Whence the box? {.medium .scrollable}\n\nThe middle of the box is the **median**.\n50% of the data are below, and 50% are above:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-45-1.png){width=960}\n:::\n:::\n\n\n## Whence the box? {.medium .scrollable}\n\nThe lower edge of the box is the **25% quantile**.\n25% of the data are below, and 75% are above:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-46-1.png){width=960}\n:::\n:::\n\n\n## Whence the box? {.medium .scrollable}\n\nThe upper edge of the box is the **75% quantile**.\n75% of the data are below, and 25% are above:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-47-1.png){width=960}\n:::\n:::\n\n\n## Box plot facts {.scrollable .small}\n\n-   A box plot is easier to read quickly than a histogram because it eliminates clutter and immediately draws your eye to those main features: center, spread, and skew;\n-   The box spans the middle 50% of the data;\n-   The width of the box is called the inner quartile range (IQR) and it measures spread;\n-   From the docs (`?geom_boxplot`):\n\n> The upper whisker extends from the hinge to the largest value no further than 1.5 \\* IQR from the hinge (where IQR is the inter-quartile range, or distance between the first and third quartiles).\n> The lower whisker extends from the hinge to the smallest value at most 1.5 \\* IQR of the hinge.\n> Data beyond the end of the whiskers are called \"outlying\" points and are plotted individually.\n\n## Box plots obscure modality\n\nSame box plot:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-48-1.png){width=960}\n:::\n:::\n\n\n## Box plots obscure modality\n\nVery different distributions:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-49-1.png){width=960}\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  summarize(\n    mean_trump_perc = mean(trump16),\n    median_trump_perc = median(trump16),\n    sd = sd(trump16),\n    iqr = IQR(trump16),\n    q25 = quantile(trump16, 0.25),\n    q75 = quantile(trump16, 0.75)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  mean_trump_perc median_trump_perc    sd   iqr   q25   q75\n            <dbl>             <dbl> <dbl> <dbl> <dbl> <dbl>\n1            45.9              48.7  16.8  23.3  34.8  58.1\n```\n\n\n:::\n:::\n\n\n## What does this code do? {.scrollable .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  summarize(\n    gimme_my_mean = mean(trump16),\n    gimme_my_median = median(trump16)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  gimme_my_mean gimme_my_median\n          <dbl>           <dbl>\n1          45.9            48.7\n```\n\n\n:::\n:::\n\n\n-   `summarize` creates a *new* data frame that stores the summaries;\n-   You can compute as many summaries as you want;\n-   To the left of the equal signs are your choice of *column names* in the new data frame you are creating. You can type whatever you want here (within reason);\n-   To the right of the equal signs is `R` code that computes the summaries. You must use the correct command names (case sensitive): `mean`, `median`, `quantile`, `sd`, `var`, etc;\n-   If you want to learn what these do, read the documentation (eg `?quantile`).\n\n## Distribution of votes for Trump in the 2016 election {.scrollable .smaller}\n\n::: question\nDescribe the distribution of percent of vote received by Trump in 2016 Presidential Election from Congressional Districts.\n:::\n\n-   Shape: [The distribution of votes for Trump in the 2016 election from Congressional Districts is **unimodal and left-skewed**.]{.fragment}\n\n-   Unusual observations: [-]{.fragment}\n\n-   Center: [The percent of vote received by Trump in the 2016 Presidential Election from a **typical** Congressional Districts is 48.7%.]{.fragment}\n\n-   Spread: [In the **middle 50%** of Congressional Districts, 34.8% to 58.1% of voters voted for Trump in the 2016 Presidential Election.]{.fragment}\n\n## Josh's Wordbank for SOCS\n\n- Shape: Unimodal, biodmoal, multimodal symmetric, leftskewed, rightskewed\n- Center: Report mean or median (depending on skew)\n- Outliers: Report unusual observations or anything past cutoff \n- Spread: How stuff is spread out, can report IQR, range, standard deviation (maybe later)\n\n# Bivariate analysis\n\n## Bivariate analysis\n\nAnalyzing the relationship between two variables:\n\n::: incremental\n-   Numerical + numerical: scatterplot\n\n-   Numerical + categorical: side-by-side box plots, violin plots, etc.\n\n-   Categorical + categorical: stacked bar plots\n\n-   Using an aesthetic (e.g., fill, color, shape, etc.) or facets to represent the second variable in any plot\n:::\n\n## Side-by-side box plots\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"|2|3-6|4|5|8\"}\nggplot(\n  gerrymander, \n  aes(\n    x = trump16, \n    y = gerry\n    )\n  ) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-52-1.png){width=960}\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  # do the following for each level of gerry\n  summarize(\n    min = min(trump16),\n    q25 = quantile(trump16, 0.25),\n    median = median(trump16),\n    q75 = quantile(trump16, 0.75),\n    max = max(trump16),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    min   q25 median   q75   max\n  <dbl> <dbl>  <dbl> <dbl> <dbl>\n1   4.9  34.8   48.7  58.1  80.4\n```\n\n\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  filter(gerry == \"low\") |>\n  summarize(\n    min = min(trump16),\n    q25 = quantile(trump16, 0.25),\n    median = median(trump16),\n    q75 = quantile(trump16, 0.75),\n    max = max(trump16),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    min   q25 median   q75   max\n  <dbl> <dbl>  <dbl> <dbl> <dbl>\n1   4.9  36.3   48.4  54.7  74.9\n```\n\n\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  filter(gerry == \"mid\") |>\n  summarize(\n    min = min(trump16),\n    q25 = quantile(trump16, 0.25),\n    median = median(trump16),\n    q75 = quantile(trump16, 0.75),\n    max = max(trump16),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    min   q25 median   q75   max\n  <dbl> <dbl>  <dbl> <dbl> <dbl>\n1   6.8  34.8   48.0  57.9  79.9\n```\n\n\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  filter(gerry == \"high\") |>\n  summarize(\n    min = min(trump16),\n    q25 = quantile(trump16, 0.25),\n    median = median(trump16),\n    q75 = quantile(trump16, 0.75),\n    max = max(trump16),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    min   q25 median   q75   max\n  <dbl> <dbl>  <dbl> <dbl> <dbl>\n1   9.2  33.5   50.5  60.8  80.4\n```\n\n\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  group_by(gerry) |>\n  summarize(\n    min = min(trump16),\n    q25 = quantile(trump16, 0.25),\n    median = median(trump16),\n    q75 = quantile(trump16, 0.75),\n    max = max(trump16),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  gerry   min   q25 median   q75   max\n  <fct> <dbl> <dbl>  <dbl> <dbl> <dbl>\n1 low     4.9  36.3   48.4  54.7  74.9\n2 mid     6.8  34.8   48.0  57.9  79.9\n3 high    9.2  33.5   50.5  60.8  80.4\n```\n\n\n:::\n:::\n\n\n## Density plots\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"|4|5|8\"}\nggplot(\n  gerrymander, \n  aes(\n    x = trump16, \n    color = gerry\n    )\n  ) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-58-1.png){width=960}\n:::\n:::\n\n\n## Filled density plots\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"6\"}\nggplot(\n  gerrymander, \n  aes(\n    x = trump16, \n    color = gerry,\n    fill = gerry\n    )\n  ) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-59-1.png){width=960}\n:::\n:::\n\n\n## Better filled density plots {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"5\"}\nggplot(\n  gerrymander, \n  aes(x = trump16, color = gerry, fill = gerry)\n  ) +\n  geom_density(alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-60-1.png){width=960}\n:::\n:::\n\n\n## Better colors\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"7-8\"}\nggplot(\n  gerrymander, \n  aes(x = trump16, color = gerry, fill = gerry)\n  ) +\n  geom_density(alpha = 0.5) +\n  scale_color_colorblind() +\n  scale_fill_colorblind()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-61-1.png){width=960}\n:::\n:::\n\n\n## Violin plots {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"5\"}\nggplot(\n  gerrymander, \n  aes(x = trump16, y = gerry, color = gerry)\n  ) +\n  geom_violin() +\n  scale_color_colorblind() +\n  scale_fill_colorblind()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-62-1.png){width=960}\n:::\n:::\n\n\n## Multiple geoms {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"6\"}\nggplot(\n  gerrymander, \n  aes(x = trump16, y = gerry, color = gerry)\n  ) +\n  geom_violin() +\n  geom_point() +\n  scale_color_colorblind() +\n  scale_fill_colorblind()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-63-1.png){width=960}\n:::\n:::\n\n\n## Multiple geoms {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"6\"}\nggplot(\n  gerrymander, \n  aes(x = trump16, y = gerry, color = gerry)\n  ) +\n  geom_violin() +\n  geom_jitter() +\n  scale_color_colorblind() +\n  scale_fill_colorblind()\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-64-1.png){width=960}\n:::\n:::\n\n\n## Remove legend {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"9\"}\nggplot(\n  gerrymander, \n  aes(x = trump16, y = gerry, color = gerry)\n  ) +\n  geom_violin() +\n  geom_jitter() +\n  scale_color_colorblind() +\n  scale_fill_colorblind() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](04-exploring-data-1_files/figure-revealjs/unnamed-chunk-65-1.png){width=960}\n:::\n:::\n\n\n# Multivariate analysis\n\n## Multivariate analysis {.scrollable .smaller}\n\nAnalyzing the relationship between multiple variables:\n\n::: incremental\n-   In general, one variable is identified as the **outcome** of interest\n\n-   The remaining variables are **predictors** or **explanatory variables**\n\n-   Plots for exploring multivariate relationships are the same as those for bivariate relationships, but **conditional** on one or more variables\n\n    -   Conditioning can be done via faceting or aesthetic mappings (e.g., scatterplot of `y` vs. `x1`, colored by `x2`, faceted by `x3`)\n\n-   Summary statistics for exploring multivariate relationships are the same as those for bivariate relationships, but **conditional** on one or more variables\n\n    -   Conditioning can be done via grouping (e.g., correlation between `y` and `x1`, grouped by levels of `x2` and `x3`)\n:::\n\n# Application exercise {.smaller}\n\n## ae\\-04\\-gerrymander\\-explore\\-I\n\n::: appex\n-   Go to your ae project in RStudio.\n\n-   If you haven't yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   If you haven't yet done so, click Pull to get today's application exercise file: *ae\\-04\\-gerrymander\\-explore\\-I\\.qmd*.\n\n-   Work through the AE and RCP your edits by the end of class.\n:::\n",
    "supporting": [
      "04-exploring-data-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}